[repository]
name = "hyprmagnet"
authors = ["Dregu"]
commit_pins = [
    ["521ece463c4a9d3d128670688a34756805a4328f", "23dd84cb292a1094b3ba4a66a539678158058614"], # 0.54.3
    ["a0136d8c04687bb36eb8a28eb9d1ff92aea99704", "3f4260012d7f8054dcf29cc614e8cac25aa91d29"], # 0.55.4
]

[hyprmagnet]
description = "Move mouse events from just outside a tiled window (i.e. from outer gaps and borders) to just inside the window, to click browser tabs and scrollbars without having to aim inside the window."
authors = ["Dregu"]
output = "libhyprmagnet.so"
build = ["make"]
